# Generated by Django 2.2.7 on 2019-12-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_id', models.AutoField(db_column='user_id', max_length=8, primary_key=True, serialize=False, verbose_name='用户ID')),
                ('user_account', models.CharField(db_index=True, max_length=25, unique=True, verbose_name='账号')),
                ('user_name', models.CharField(max_length=25, verbose_name='用户名')),
                ('email', models.EmailField(db_index=True, max_length=20, verbose_name='邮箱')),
                ('user_url', models.CharField(max_length=64, verbose_name='头像')),
                ('user_gender', models.SmallIntegerField(choices=[(0, 'female'), (1, 'male')], default=0, verbose_name='性别')),
                ('user_phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('user_credit', models.IntegerField(default=0, verbose_name='用户积分')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态(1为账户存在，0为不存在)')),
            ],
            options={
                'db_table': 'tb_user',
            },
        ),
    ]
