# Generated by Django 2.2.7 on 2019-12-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('sequence_id', models.AutoField(max_length=8, primary_key=True, serialize=False, verbose_name='聊天记录ID')),
                ('from_id', models.CharField(max_length=8, verbose_name='发送者id')),
                ('to_id', models.CharField(max_length=8, verbose_name='接受者id')),
                ('chat_send_time', models.DateTimeField(auto_now=True, verbose_name='发送时间')),
                ('chat_content', models.TextField(verbose_name='私信内容')),
            ],
            options={
                'db_table': 'tb_message',
            },
        ),
    ]
